Update upgrade.yml

diff --git a/.github/workflows/upgrade.yml b/.github/workflows/upgrade.yml
--- a/.github/workflows/upgrade.yml
+++ b/.github/workflows/upgrade.yml
@@ -25,20 +25,34 @@ jobs:
       - uses: actions/checkout@v2
 
       # Runs a single command using the runners shell
-      - name: Run a one-line script
+      - name: "'\033[0;34m' info '\033[0m' initiating update script"
         run: echo Hello, world! Updating dependencies...
 
       # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: "'\033[0;34m' info '\033[0m' running commands"
         run: |
-          echo Checking for YARN
+          echo "'\033[0;34m' info '\033[0m' checking for yarn"
           yarn -v
           if [ $? == 0 ]; then
+            echo "'\033[0;34m' info '\033[0m' running yarn upgrade"
             yarn upgrade
           else
+            echo "'\033[0;31m' err '\033[0m' yarn not found"
+            echo "'\033[0;34m' info '\033[0m' running npm update"
             npm update
           fi
-          git add .
-          git commit . -m "updated dependencies"
-          if [ $? != 1 ]; then
-          git push origin master
+          
+          if [ $? == 0 ]; then
+            git add .
+            git commit . -m "updated dependencies"
+            if [ $? != 1 ]; then
+              git push origin master
+              
+            else
+              echo "'\033[0;34m' info '\033[0m' repo is already up to date."
+            fi
+          else
+            echo "'\033[0;31m' err '\033[0m' something went wrong, unable to upgrade."
+          fi
+          
+              
